repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
        exclude: '^data/'
      - id: end-of-file-fixer
        exclude: '^data/'
      - id: debug-statements
      - id: check-yaml
  - repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
        exclude: '^data/'
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
