dist: xenial
sudo: false
cache: pip
language: python
python:
  - 3.8
stages:
  - lint
  - docs
  - test
jobs:
  include:
    # lint stage
    - stage: lint
      env: TOXENV=manifest
    - env: TOXENV=flake8
    - env: TOXENV=pyroma
    # docs stage
    - stage: docs
      env: TOXENV=doc8
    - env: TOXENV=docs
    # test stage
    - stage: test
      env: TOXENV=py
install:
- pip install --upgrade pip
- pip install tox
- pip install codecov
- pip install coverage
script:
- tox
after_success:
- tox -e coverage-report
- codecov

