name: code-formatter
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Linting
        run: |
          uvx pre-commit run --files src/*
          uvx pre-commit run --files docs/*
